site_name: "FFTMatvec Documentation"

repo_url: "https://github.com/s769/FFTMatvec"

theme:
  name: 'material'
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  # Add the arithmatex extension here:
  - pymdownx.arithmatex:
      generic: true

# Add the JavaScript loaders here:
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdoxy:
      projects:
        FFTMatvec: 
          src-dirs: src/ 
          full-doc: True 
          doxy-cfg: 
            FILE_PATTERNS: "Comm.*pp main.cpp Matrix.*pp shared.hpp tester.*pp utils.*pp util_kernels.cu util_kernels.hpp Vector.*pp error_checkers.h comm_error_checkers.h" 
            RECURSIVE: True 

nav:
  - Getting Started: "getting_started.md"
  - I/O and Data Formats: "io_format.md"
  - Single-GPU Block Toeplitz Inverse: "block_toeplitz_inverse_single_gpu.md"
  - Block Toeplitz Inverse Benchmarks: "benchmark_result.md"
  - pyFFTMatvec: "python_bindings.md"
  - API Reference:
    - "Classes":
        - "Comm": "FFTMatvec/classComm.md"
        - "Matrix": "FFTMatvec/classMatrix.md"
        - "Vector": "FFTMatvec/classVector.md"
    - "Namespaces":
        - "Utils": "FFTMatvec/namespaceUtils.md"
        - "UtilKernels": "FFTMatvec/namespaceUtilKernels.md"
        - "Tester": "FFTMatvec/namespaceTester.md"
  - LICENSE: "license.md"
